In [3]:
import numpy as np



In [ ]:
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find Country index with max gold

In [6]:
# Define the data
olympic_country = np.array(['GBR', 'Chine', 'RUS', 'US', 'KOR, JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the maximum gold medals
max_gold_index = np.argmax(olympic_country_gold)

# Get the country with the maximum gold medals
country_with_max_gold = olympic_country[max_gold_index]

print(f"The country with the maximum gold medals is {country_with_max_gold} at index {max_gold_index}.")

The country with the maximum gold medals is US at index 3.


# 2. Country with Max Gold

In [12]:
import numpy as np

# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Find the index of the country with the max gold medals
max_gold_index = np.argmax(olympic_country_gold)

# Get the country with the max gold medals
country_with_max_gold = olympic_country[max_gold_index]

print("Country with the most gold medals:", country_with_max_gold)

Country with the most gold medals: US


# 3. Find Countries with More than 20 Gold

In [9]:
# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])

# Create a boolean mask for countries with more than 20 gold medals
mask = olympic_country_gold > 20

# Use the mask to filter the countries
countries_with_more_than_20_gold = olympic_country[mask]

print("Countries with more than 20 gold medals:", countries_with_more_than_20_gold)

Countries with more than 20 gold medals: ['GBR' 'China' 'RUS' 'US']


# 4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals

In [10]:
import numpy as np

# Assuming you have the data stored in the following arrays
olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# Calculate and print each country's name with the number of gold medals and total medals
for i in range(len(olympic_country)):
    country = olympic_country[i]
    gold = olympic_country_gold[i]
    silver = olympic_country_silver[i]
    bronze = olympic_country_bronze[i]
    total_medals = gold + silver + bronze
    print(f"Country: {country}, Gold Medals: {gold}, Total Medals: {total_medals}")

Country: GBR, Gold Medals: 29, Total Medals: 65
Country: China, Gold Medals: 38, Total Medals: 88
Country: RUS, Gold Medals: 24, Total Medals: 81
Country: US, Gold Medals: 46, Total Medals: 103
Country: KOR, Gold Medals: 13, Total Medals: 28
Country: JPN, Gold Medals: 7, Total Medals: 38
Country: GER, Gold Medals: 11, Total Medals: 36


# 1. Create a 3x3x3 array with random values.

In [13]:
import numpy as np
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.48074543 0.66607089 0.03014761]
  [0.176452   0.5672356  0.92511377]
  [0.50178349 0.23857957 0.18480939]]

 [[0.15218969 0.75553821 0.01813953]
  [0.93500695 0.34183355 0.2518215 ]
  [0.84846274 0.68614971 0.51351038]]

 [[0.1227467  0.23958522 0.36590624]
  [0.54068412 0.36466656 0.71488646]
  [0.06073988 0.80738589 0.50137612]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [18]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the even rows and columns with 1
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [20]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)

print("Original Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.53362488 0.53950354 0.02819541 0.38043913 0.98093999]
 [0.32061138 0.90747204 0.97274159 0.5182073  0.36044875]
 [0.30000999 0.37903112 0.95869751 0.14254207 0.2335364 ]
 [0.5990552  0.56955616 0.00511614 0.40503824 0.46418739]
 [0.08622913 0.23004703 0.42775389 0.30234512 0.18948816]]

Normalized Matrix:
[[ 0.36168759  0.38290071 -1.46215354 -0.19108284  1.9758232 ]
 [-0.40697116  1.71071424  1.94623927  0.30605329 -0.26321808]
 [-0.48131121 -0.19616364  1.89556125 -1.04953387 -0.72118104]
 [ 0.59779276  0.49134554 -1.54543503 -0.10231702  0.11112256]
 [-1.25273898 -0.7337724  -0.02034766 -0.47288493 -0.88012902]]


# 5. How to find common values between two arrays?

In [21]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print(common_values)


[3 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [24]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Calculate yesterday's date by subtracting one day
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date by adding one day
tomorrow = today + timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime('%d-%m-%Y')
yesterday_str = yesterday.strftime('%d-%m-%Y')
tomorrow_str = tomorrow.strftime('%d-%m-%Y')

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)


Yesterday: 20-09-2023
Today: 21-09-2023
Tomorrow: 22-09-2023


# 7. Consider two random array A and B, check if they are equal


In [25]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the arrays are equal element-wise
elementwise_equal = (A == B).all()

if elementwise_equal:
    print("Arrays A and B are equal element-wise.")
else:
    print("Arrays A and B are not equal element-wise.")

    

Arrays A and B are not equal element-wise.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [26]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original random vector:")
print(random_vector)


Original random vector:
[0.14161112 0.26793149 0.84470435 0.11377951 0.17506438 0.2507231
 0.29822502 0.24004103 0.         0.57650985]


# 9. How to print all the values of an array?


In [28]:
#List:

my_list = [1, 2, 3, 4, 5]
a=np.ndarray(my_list)
for value in a:
    print(value)


[[[[6.95310536e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 6.95310546e-310 0.00000000e+000
    0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 1.42173718e-312
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000]
   [0.00000000e+0

In [29]:
#Using a list comprehension:

my_list = [1, 2, 3, 4, 5]
[print(value) for value in my_list]


1
2
3
4
5


[None, None, None, None, None]

In [30]:
#NumPy Array:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1 2 3 4 5]


# 10.Subtract the mean of each row of a matrix

In [31]:
import numpy as np

# Create a sample matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector. How to add one to each element indexed by a second vector(be careful with repeated indices)? Code in Python.

In [32]:
import numpy as np

# Your initial vector
initial_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices = np.array([0, 2, 3])

# Create a new vector to store the results
result_vector = initial_vector.copy()

# Add one to each element at the specified indices
result_vector[indices] += 1

print(result_vector)

[2 2 4 5 5]


# 12. How to get a Diagonal of Dot product?

In [33]:
import numpy as np

# Create two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[30 69 90]


# 12.How to get a Diagonal of Dot product ?

In [34]:
import numpy as np

# Create two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[30 69 90]


# 13.How to Find the Most Frequent Value in an Array?

In [35]:
import numpy as np

# Sample array
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])

# Use the `unique` function to get unique values and their counts
unique_values, counts = np.unique(my_array, return_counts=True)

# Find the index of the maximum count, which corresponds to the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")

The most frequent value is 4 with 4 occurrences.


# 14.How to get the n-largest values of an array?

In [36]:
import numpy as np

# Create an example array
arr = np.array([5, 2, 8, 1, 7, 3])

# Set the value of 'n' to get the n-largest values
n = 3

# Use partition to get the n-largest values
n_largest = np.partition(arr, -n)[-n:]

print(n_largest)

[5 7 8]


# 15.How to Create a Record Array from a Regular Array?

In [37]:
import numpy as np

# Create a regular array with data
regular_array = np.array([(1, 'rohan', 25),
                           (2, 'rohit', 30),
                           (3, 'vignesh', 22)],
                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

# Print the record array
print(record_array)

((1, 'rohan', 25), (2, 'rohit', 30), (3, 'vignesh', 22))


# 16.How to swap two rows of an array ?

In [38]:
import numpy as np

# Create a sample 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows (for example, swapping rows 0 and 2)
array[[0, 2]] = array[[2, 0]]

# Now, 'array' will have rows 0 and 2 swapped
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write Python code to reshape to the next dimension of numPy array.

In [39]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(-1, original_array.shape[0])

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
